let nama = "Ali";
let umur =27;
let jk=true;
let kosong =null;
let tidakTahu;
let buah = ["apel",  "jeruk", "nanas"];
console.log(nama);
console.log(umur);
console.log(jk);
console.log(tidakTahu);
console.log(buah);
